#!/usr/bin/env python
import os
import sys
import argparse


def run(command, cwd=None):
    return os.system('/bin/bash -c "{0}"'.format(command))


def register_arguments():
    parser = argparse.ArgumentParser()

    parser.add_argument('-o', '--offline-install-path', help='The dir path to install pip packages from.')

    return parser.parse_args()


args = register_arguments()

local_pip_packages = '--no-index --find-links=file:{0}'.format(
    args.offline_install_path) if args.offline_install_path is not None else ''

# create venv, activate it and install requirements to it (from a local dir if it exists)
command = 'virtualenv venv && source venv/bin/activate && pip install {0} -r requirements.txt'.format(
    local_pip_packages)

run(command)

# symlink to run
ln_cmd = 'ln -sF {0}/run /usr/local/bin/clt'.format(os.getcwd())

# first try without sudo, then with
retval = run(ln_cmd)

if retval != 0:
    retval = run('sudo {0}'.format(ln_cmd))

sys.exit(retval)
